# Generated by Django 5.2.1 on 2025-05-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plantid_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantimage",
            name="predicted_label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
